# Generated by Django 5.1.7 on 2026-04-06 08:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('hod', 'HOD')], max_length=10)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('branches', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_first_login', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Academic_Subject',
            fields=[
                ('SubjectCode', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(50)])),
                ('SubjectName', models.CharField(max_length=255)),
                ('Semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Branch', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'academic_subject',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faculty_Teacher',
            fields=[
                ('TeacherID', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='Teacher ID')),
                ('FullName', models.CharField(max_length=255)),
                ('Designation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'faculty_teacher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Academic_Allocation',
            fields=[
                ('AllocationID', models.AutoField(primary_key=True, serialize=False)),
                ('TargetBranch', models.CharField(max_length=50)),
                ('Target_Year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Target_Semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Target_Section', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('SubjectCode', models.ForeignKey(db_column='SubjectCode', on_delete=django.db.models.deletion.CASCADE, to='feedback_app.academic_subject')),
                ('TeacherID', models.ForeignKey(db_column='TeacherID', on_delete=django.db.models.deletion.CASCADE, to='feedback_app.faculty_teacher')),
            ],
            options={
                'db_table': 'academic_allocation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback_Response',
            fields=[
                ('ResponseID', models.AutoField(primary_key=True, serialize=False)),
                ('Q1_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q2_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q3_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q4_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q5_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q6_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q7_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q8_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q9_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q10_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Comments', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('AllocationID', models.ForeignKey(db_column='AllocationID', on_delete=django.db.models.deletion.CASCADE, to='feedback_app.academic_allocation')),
            ],
            options={
                'db_table': 'feedback_response',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback_SubmissionLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('EnrollmentNo', models.CharField(max_length=50)),
                ('AllocationID', models.ForeignKey(db_column='AllocationID', on_delete=django.db.models.deletion.CASCADE, to='feedback_app.academic_allocation')),
                ('ResponseID', models.ForeignKey(db_column='ResponseID', on_delete=django.db.models.deletion.CASCADE, to='feedback_app.feedback_response')),
            ],
            options={
                'db_table': 'feedback_submissionlog',
                'managed': True,
            },
        ),
    ]
