# Generated by Django 5.1.7 on 2026-08-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_response',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]