# Generated by Django 5.1.7 on 2026-08-10 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_add_is_archived_to_feedback_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academic_allocation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='academic_subject',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='faculty_teacher',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedback_response',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feedback_submissionlog',
            options={'managed': False},
        ),
    ]
