# Generated by Django 5.1.7 on 2026-08-06 23:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackResponseArchive',
            fields=[
                ('ResponseID', models.AutoField(primary_key=True, serialize=False)),
                ('Q1_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q2_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q3_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q4_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q5_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q6_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q7_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q8_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q9_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Q10_Rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Comments', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('is_archived', models.BooleanField(default=False)),
                ('AllocationID', models.ForeignKey(db_column='AllocationID', help_text='References the live academic allocation. PROTECT (instead of CASCADE) ensures archived rows can never be silently destroyed when a lookup allocation is deleted.', on_delete=django.db.models.deletion.PROTECT, to='feedback_app.academic_allocation')),
            ],
            options={
                'verbose_name': 'Archived Feedback Response',
                'verbose_name_plural': 'Archived Feedback Responses',
                'db_table': 'feedback_response_archive',
            },
        ),
    ]