# Generated by Django 5.1.7 on 2026-08-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackResponseArchive',
        ),
    ]